# Generated by Django 4.1.5 on 2023-07-17 12:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('locality', models.CharField(max_length=200)),
                ('mobile', models.IntegerField(default=0)),
                ('zipcode', models.IntegerField()),
                ('citystate', models.CharField(choices=[('Delhi NCR', 'Delhi NCR'), ('Hyderabad', 'Hyderabad'), ('Jaipur', 'Jaipur'), ('Kolkata', 'Kolkata'), ('Lucknow', 'Lucknow'), ('Mumbai', 'Mumbai'), ('Mysore', 'Mysore'), ('Nashik', 'Nashik'), ('Pune', 'Pune'), ('Surat', 'Surat'), ('Vijayawada', 'Vijayawada'), ('Warangal', 'Warangal'), ('Bangalore', 'Bangalore'), ('Chandigarh', 'Chandigarh'), ('Chennai', 'Chennai'), ('Coimbatore', 'Coimbatore')], max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
