# Generated by Django 4.1.5 on 2023-07-27 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_wishlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='citystate',
            new_name='city',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('CR', 'Curd'), ('ML', 'Milk'), ('LS', 'Lassi'), ('EG', 'Eggs'), ('PN', 'Paneer'), ('GH', 'Ghee'), ('CW', 'Coconut Water'), ('BD', 'Breads'), ('MS', 'Milkshakes')], max_length=2),
        ),
    ]
